# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "U:/Example_Systems/DE1/DE1_Basic_Computer/verilog/DE1_Basic_Computer.qpf"
project_close